//! Adapter connecting `MilestoneEscrow` to `soroban-invariant-kit-core`.

use crate::contract::unfixed::{UnfixedMilestoneEscrow, UnfixedMilestoneEscrowClient};
use crate::contract::{MilestoneEscrow, MilestoneEscrowClient, MilestoneStatus};
use soroban_invariant_kit_core::{
    ActionResult, ContractAdapter, EscrowActionKind, EscrowAdapter, EscrowStateSnapshot,
    MilestoneSnapshot, MilestoneStatusKind,
};
use soroban_sdk::{
    testutils::Address as _, testutils::Ledger as _, token, vec, Address, Env,
};

#[derive(thiserror::Error, Debug)]
pub enum EscrowAdapterError {
    #[error("Simulation setup error: {0}")]
    SetupError(String),
    #[error("Contract query error: {0}")]
    QueryError(String),
}

/// Abstract actions generated by fuzzer / property tests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EscrowAction {
    /// Fund the escrow with the required milestone amounts.
    Fund,
    /// Mark a milestone delivered by the freelancer.
    MarkDelivered { milestone_id: u32 },
    /// Approve and release a milestone in full.
    ApproveMilestone { milestone_id: u32 },
    /// Approve and release a partial milestone amount.
    ApprovePartial { milestone_id: u32, amount: i128 },
    /// Freelancer claims auto-release after duration passes.
    ClaimAutoRelease { milestone_id: u32, advance_seconds: u64 },
    /// Client or freelancer raises a dispute on a milestone.
    RaiseDispute { milestone_id: u32 },
    /// Arbiter resolves a dispute.
    ResolveDispute {
        milestone_id: u32,
        release_to_freelancer: bool,
    },
}

/// State snapshot captured by the adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EscrowAdapterState {
    pub snapshot: EscrowStateSnapshot,
}

/// Adapter for testing the hardened `MilestoneEscrow` contract.
pub struct EscrowContractAdapter {
    pub env: Env,
    pub contract_id: Address,
    pub token_id: Address,
    pub admin: Address,
    pub client: Address,
    pub freelancer: Address,
    pub arbiter: Address,
    pub initial_milestone_amounts: Vec<i128>,
}

impl EscrowContractAdapter {
    pub fn setup_with_amounts(milestone_amounts: &[i128]) -> Result<Self, EscrowAdapterError> {
        let env = Env::default();
        env.mock_all_auths();

        let admin = Address::generate(&env);
        let client = Address::generate(&env);
        let freelancer = Address::generate(&env);
        let arbiter = Address::generate(&env);

        let token_id = env
            .register_stellar_asset_contract_v2(admin.clone())
            .address();
        let token_admin = token::StellarAssetClient::new(&env, &token_id);

        let total_deposit: i128 = milestone_amounts.iter().sum();
        token_admin.mint(&client, &(total_deposit * 2)); // extra buffer for multiple tests

        let contract_id = env.register(MilestoneEscrow, ());
        let escrow_client = MilestoneEscrowClient::new(&env, &contract_id);

        let mut sdk_amounts = vec![&env];
        for &amt in milestone_amounts {
            sdk_amounts.push_back(amt);
        }

        escrow_client
            .try_initialize(
                &admin,
                &client,
                &freelancer,
                &arbiter,
                &token_id,
                &604800, // 7 days auto-release
                &sdk_amounts,
            )
            .map_err(|e| EscrowAdapterError::SetupError(format!("{:?}", e)))?
            .map_err(|e| EscrowAdapterError::SetupError(format!("{:?}", e)))?;

        Ok(Self {
            env,
            contract_id,
            token_id,
            admin,
            client,
            freelancer,
            arbiter,
            initial_milestone_amounts: milestone_amounts.to_vec(),
        })
    }
}

impl ContractAdapter for EscrowContractAdapter {
    type Action = EscrowAction;
    type State = EscrowAdapterState;
    type Error = EscrowAdapterError;

    fn setup() -> Result<Self, Self::Error> {
        Self::setup_with_amounts(&[3000, 7000])
    }

    fn snapshot(&self) -> Result<Self::State, Self::Error> {
        let escrow_client = MilestoneEscrowClient::new(&self.env, &self.contract_id);
        let token_client = token::Client::new(&self.env, &self.token_id);

        let job = escrow_client
            .try_get_job()
            .map_err(|e| EscrowAdapterError::QueryError(format!("{:?}", e)))?
            .map_err(|e| EscrowAdapterError::QueryError(format!("{:?}", e)))?;

        let token_balance = token_client.balance(&self.contract_id);

        let mut milestones = Vec::new();
        let mut total_released = 0i128;
        let mut total_refunded = 0i128;
        let mut is_disputed = false;

        for (idx, m) in job.milestones.iter().enumerate() {
            let status_kind = match m.status {
                MilestoneStatus::Pending => MilestoneStatusKind::Pending,
                MilestoneStatus::Delivered => MilestoneStatusKind::Delivered,
                MilestoneStatus::PartiallyReleased => MilestoneStatusKind::PartiallyReleased,
                MilestoneStatus::Released => MilestoneStatusKind::Released,
                MilestoneStatus::Disputed => MilestoneStatusKind::Disputed,
                MilestoneStatus::Refunded => MilestoneStatusKind::Refunded,
            };

            let is_milestone_disputed = m.status == MilestoneStatus::Disputed;
            if is_milestone_disputed {
                is_disputed = true;
            }

            let is_released = m.status == MilestoneStatus::Released;
            let is_refunded = m.status == MilestoneStatus::Refunded;
            let is_approved = m.status == MilestoneStatus::Delivered
                || m.status == MilestoneStatus::PartiallyReleased
                || is_released;

            total_released += m.released_amount;
            if is_refunded {
                total_refunded += m.amount.saturating_sub(m.released_amount);
            }

            milestones.push(MilestoneSnapshot {
                id: idx as u32,
                amount: m.amount,
                released_amount: m.released_amount,
                is_approved,
                is_released,
                is_refunded,
                is_disputed: is_milestone_disputed,
                status: status_kind,
            });
        }

        let total_locked = if job.funded {
            token_balance
        } else {
            0
        };

        Ok(EscrowAdapterState {
            snapshot: EscrowStateSnapshot {
                total_locked,
                total_released,
                total_refunded,
                is_funded: job.funded,
                is_disputed,
                milestones,
                contract_token_balance: Some(token_balance),
            },
        })
    }

    fn step(&mut self, action: &Self::Action) -> Result<ActionResult, Self::Error> {
        let client = MilestoneEscrowClient::new(&self.env, &self.contract_id);

        let res = match action {
            EscrowAction::Fund => match client.try_fund(&self.client) {
                Ok(Ok(())) => ActionResult::Ok,
                Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                Err(e) => ActionResult::Reverted(format!("{:?}", e)),
            },
            EscrowAction::MarkDelivered { milestone_id } => {
                match client.try_mark_delivered(&self.freelancer, milestone_id) {
                    Ok(Ok(())) => ActionResult::Ok,
                    Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                    Err(e) => ActionResult::Reverted(format!("{:?}", e)),
                }
            }
            EscrowAction::ApproveMilestone { milestone_id } => {
                match client.try_approve_milestone(&self.client, milestone_id) {
                    Ok(Ok(())) => ActionResult::Ok,
                    Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                    Err(e) => ActionResult::Reverted(format!("{:?}", e)),
                }
            }
            EscrowAction::ApprovePartial {
                milestone_id,
                amount,
            } => match client.try_approve_partial(&self.client, milestone_id, amount) {
                Ok(Ok(())) => ActionResult::Ok,
                Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                Err(e) => ActionResult::Reverted(format!("{:?}", e)),
            },
            EscrowAction::ClaimAutoRelease {
                milestone_id,
                advance_seconds,
            } => {
                // Advance ledger timestamp to test auto release
                if *advance_seconds > 0 {
                    let cur = self.env.ledger().timestamp();
                    self.env.ledger().set_timestamp(cur + *advance_seconds);
                }
                match client.try_claim_auto_release(&self.freelancer, milestone_id) {
                    Ok(Ok(())) => ActionResult::Ok,
                    Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                    Err(e) => ActionResult::Reverted(format!("{:?}", e)),
                }
            }
            EscrowAction::RaiseDispute { milestone_id } => {
                match client.try_raise_dispute(&self.client, milestone_id) {
                    Ok(Ok(())) => ActionResult::Ok,
                    Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                    Err(e) => ActionResult::Reverted(format!("{:?}", e)),
                }
            }
            EscrowAction::ResolveDispute {
                milestone_id,
                release_to_freelancer,
            } => {
                match client.try_resolve_dispute(
                    &self.arbiter,
                    milestone_id,
                    release_to_freelancer,
                ) {
                    Ok(Ok(())) => ActionResult::Ok,
                    Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                    Err(e) => ActionResult::Reverted(format!("{:?}", e)),
                }
            }
        };

        Ok(res)
    }
}

impl EscrowAdapter for EscrowContractAdapter {
    fn inspect_escrow(state: &Self::State) -> EscrowStateSnapshot {
        state.snapshot.clone()
    }

    fn classify_action(action: &Self::Action) -> Option<EscrowActionKind> {
        match action {
            EscrowAction::Fund => Some(EscrowActionKind::Fund { amount: 10000 }),
            EscrowAction::MarkDelivered { milestone_id } => {
                Some(EscrowActionKind::MarkDelivered {
                    milestone_id: *milestone_id,
                })
            }
            EscrowAction::ApproveMilestone { milestone_id } => {
                Some(EscrowActionKind::ApproveMilestone {
                    milestone_id: *milestone_id,
                })
            }
            EscrowAction::ApprovePartial {
                milestone_id,
                amount,
            } => Some(EscrowActionKind::ApprovePartial {
                milestone_id: *milestone_id,
                amount: *amount,
            }),
            EscrowAction::ClaimAutoRelease { milestone_id, .. } => {
                Some(EscrowActionKind::ClaimAutoRelease {
                    milestone_id: *milestone_id,
                })
            }
            EscrowAction::RaiseDispute { milestone_id } => {
                Some(EscrowActionKind::RaiseDispute {
                    milestone_id: *milestone_id,
                })
            }
            EscrowAction::ResolveDispute {
                milestone_id,
                release_to_freelancer,
            } => Some(EscrowActionKind::ResolveDispute {
                milestone_id: *milestone_id,
                release_to_freelancer: *release_to_freelancer,
            }),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Unfixed Adapter for Bug Reproduction
// ─────────────────────────────────────────────────────────────────────────────

/// Adapter for testing the unfixed/vulnerable version from upstream.
pub struct UnfixedEscrowContractAdapter {
    pub env: Env,
    pub contract_id: Address,
    pub token_id: Address,
    pub admin: Address,
    pub client: Address,
    pub freelancer: Address,
    pub arbiter: Address,
}

impl UnfixedEscrowContractAdapter {
    pub fn setup_unfixed() -> Result<Self, EscrowAdapterError> {
        let env = Env::default();
        env.mock_all_auths();

        let admin = Address::generate(&env);
        let client = Address::generate(&env);
        let freelancer = Address::generate(&env);
        let arbiter = Address::generate(&env);

        let token_id = env
            .register_stellar_asset_contract_v2(admin.clone())
            .address();
        let token_admin = token::StellarAssetClient::new(&env, &token_id);
        token_admin.mint(&client, &20_000);

        let contract_id = env.register(UnfixedMilestoneEscrow, ());
        let escrow_client = UnfixedMilestoneEscrowClient::new(&env, &contract_id);

        let mut sdk_amounts = vec![&env];
        sdk_amounts.push_back(5000);

        escrow_client
            .try_initialize(
                &admin,
                &client,
                &freelancer,
                &arbiter,
                &token_id,
                &604800,
                &sdk_amounts,
            )
            .map_err(|e| EscrowAdapterError::SetupError(format!("{:?}", e)))?
            .map_err(|e| EscrowAdapterError::SetupError(format!("{:?}", e)))?;

        Ok(Self {
            env,
            contract_id,
            token_id,
            admin,
            client,
            freelancer,
            arbiter,
        })
    }
}

impl ContractAdapter for UnfixedEscrowContractAdapter {
    type Action = EscrowAction;
    type State = EscrowAdapterState;
    type Error = EscrowAdapterError;

    fn setup() -> Result<Self, Self::Error> {
        Self::setup_unfixed()
    }

    fn snapshot(&self) -> Result<Self::State, Self::Error> {
        let escrow_client = UnfixedMilestoneEscrowClient::new(&self.env, &self.contract_id);
        let token_client = token::Client::new(&self.env, &self.token_id);

        let job = escrow_client
            .try_get_job()
            .map_err(|e| EscrowAdapterError::QueryError(format!("{:?}", e)))?
            .map_err(|e| EscrowAdapterError::QueryError(format!("{:?}", e)))?;

        let token_balance = token_client.balance(&self.contract_id);

        let mut milestones = Vec::new();
        let mut total_released = 0i128;
        let mut total_refunded = 0i128;
        let mut is_disputed = false;

        for (idx, m) in job.milestones.iter().enumerate() {
            let status_kind = match m.status {
                MilestoneStatus::Pending => MilestoneStatusKind::Pending,
                MilestoneStatus::Delivered => MilestoneStatusKind::Delivered,
                MilestoneStatus::PartiallyReleased => MilestoneStatusKind::PartiallyReleased,
                MilestoneStatus::Released => MilestoneStatusKind::Released,
                MilestoneStatus::Disputed => MilestoneStatusKind::Disputed,
                MilestoneStatus::Refunded => MilestoneStatusKind::Refunded,
            };

            let is_milestone_disputed = m.status == MilestoneStatus::Disputed;
            if is_milestone_disputed {
                is_disputed = true;
            }

            let is_released = m.status == MilestoneStatus::Released;
            let is_refunded = m.status == MilestoneStatus::Refunded;
            let is_approved = m.status == MilestoneStatus::Delivered
                || m.status == MilestoneStatus::PartiallyReleased
                || is_released;

            total_released += m.released_amount;
            if is_refunded {
                total_refunded += m.amount.saturating_sub(m.released_amount);
            }

            milestones.push(MilestoneSnapshot {
                id: idx as u32,
                amount: m.amount,
                released_amount: m.released_amount,
                is_approved,
                is_released,
                is_refunded,
                is_disputed: is_milestone_disputed,
                status: status_kind,
            });
        }

        let total_locked = if job.funded {
            token_balance
        } else {
            0
        };

        Ok(EscrowAdapterState {
            snapshot: EscrowStateSnapshot {
                total_locked,
                total_released,
                total_refunded,
                is_funded: job.funded,
                is_disputed,
                milestones,
                contract_token_balance: Some(token_balance),
            },
        })
    }

    fn step(&mut self, action: &Self::Action) -> Result<ActionResult, Self::Error> {
        let client = UnfixedMilestoneEscrowClient::new(&self.env, &self.contract_id);

        let res = match action {
            EscrowAction::Fund => match client.try_fund(&self.client) {
                Ok(Ok(())) => ActionResult::Ok,
                Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                Err(e) => ActionResult::Reverted(format!("{:?}", e)),
            },
            EscrowAction::RaiseDispute { milestone_id } => {
                match client.try_raise_dispute(&self.client, milestone_id) {
                    Ok(Ok(())) => ActionResult::Ok,
                    Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                    Err(e) => ActionResult::Reverted(format!("{:?}", e)),
                }
            }
            EscrowAction::ResolveDispute {
                milestone_id,
                release_to_freelancer,
            } => {
                match client.try_resolve_dispute(
                    &self.arbiter,
                    milestone_id,
                    release_to_freelancer,
                ) {
                    Ok(Ok(())) => ActionResult::Ok,
                    Ok(Err(e)) => ActionResult::Reverted(format!("{:?}", e)),
                    Err(e) => ActionResult::Reverted(format!("{:?}", e)),
                }
            }
            _ => ActionResult::Skipped("Action not supported on unfixed contract".into()),
        };

        Ok(res)
    }
}

impl EscrowAdapter for UnfixedEscrowContractAdapter {
    fn inspect_escrow(state: &Self::State) -> EscrowStateSnapshot {
        state.snapshot.clone()
    }

    fn classify_action(action: &Self::Action) -> Option<EscrowActionKind> {
        match action {
            EscrowAction::Fund => Some(EscrowActionKind::Fund { amount: 5000 }),
            EscrowAction::RaiseDispute { milestone_id } => {
                Some(EscrowActionKind::RaiseDispute {
                    milestone_id: *milestone_id,
                })
            }
            EscrowAction::ResolveDispute {
                milestone_id,
                release_to_freelancer,
            } => Some(EscrowActionKind::ResolveDispute {
                milestone_id: *milestone_id,
                release_to_freelancer: *release_to_freelancer,
            }),
            _ => None,
        }
    }
}
