//! Adapter connecting `SplitContract` to `soroban-invariant-kit-core`.

use crate::contract::{
    RecipientShare, SplitContract, SplitContractClient,
};
use soroban_invariant_kit_core::{
    ActionResult, ContractAdapter, RecipientShareSnapshot, SplitActionKind, SplitAdapter,
    SplitBatchSnapshot, SplitStateSnapshot,
};
use soroban_sdk::{
    testutils::Address as _, token, vec as sdk_vec, Address, Env, Vec as SdkVec,
};

#[derive(thiserror::Error, Debug)]
pub enum SplitAdapterError {
    #[error("Simulation setup error: {0}")]
    SetupError(String),
    #[error("Contract query error: {0}")]
    QueryError(String),
}

/// Abstract actions generated by fuzzer / property tests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SplitAction {
    /// Sender deposits tokens to be split proportionally across recipients.
    DepositAndSplit { amount: i128 },
    /// Recipient claims their accumulated allocated tokens.
    Claim { recipient_idx: usize },
    /// Admin updates the recipient share distribution.
    UpdateShares { shares_bps: Vec<u32> },
}

/// State snapshot captured by the adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SplitAdapterState {
    pub snapshot: SplitStateSnapshot,
    pub sender_token_balance: i128,
}

/// Adapter for testing `SplitContract`.
pub struct SplitContractAdapter {
    pub env: Env,
    pub contract_id: Address,
    pub token_id: Address,
    pub admin: Address,
    pub sender: Address,
    pub recipients: Vec<Address>,
}

impl SplitContractAdapter {
    pub fn setup_with_recipients(
        recipients_count: usize,
        initial_mint: i128,
    ) -> Result<Self, SplitAdapterError> {
        let env = Env::default();
        env.mock_all_auths();

        let admin = Address::generate(&env);
        let sender = Address::generate(&env);

        let mut recipients = Vec::new();
        for _ in 0..recipients_count {
            recipients.push(Address::generate(&env));
        }

        let token_id = env
            .register_stellar_asset_contract_v2(admin.clone())
            .address();
        let token_admin = token::StellarAssetClient::new(&env, &token_id);
        token_admin.mint(&sender, &initial_mint);

        let contract_id = env.register(SplitContract, ());
        let client = SplitContractClient::new(&env, &contract_id);

        // Standard 3-way split: 50% (5,000 bps), 30% (3,000 bps), 20% (2,000 bps)
        let initial_bps = match recipients_count {
            1 => vec![10_000],
            2 => vec![6_000, 4_000],
            3 => vec![5_000, 3_000, 2_000],
            _ => {
                let equal_share = 10_000 / (recipients_count as u32);
                let remainder = 10_000 % (recipients_count as u32);
                let mut shares = vec![equal_share; recipients_count];
                shares[0] += remainder;
                shares
            }
        };

        let mut sdk_recipients = sdk_vec![&env];
        for (i, rec) in recipients.iter().enumerate() {
            sdk_recipients.push_back(RecipientShare {
                recipient: rec.clone(),
                share_bps: initial_bps[i],
            });
        }

        client
            .try_initialize(&admin, &token_id, &sdk_recipients)
            .map_err(|e| SplitAdapterError::SetupError(format!("{:?}", e)))?
            .map_err(|e| SplitAdapterError::SetupError(format!("{:?}", e)))?;

        Ok(Self {
            env,
            contract_id,
            token_id,
            admin,
            sender,
            recipients,
        })
    }
}

impl ContractAdapter for SplitContractAdapter {
    type Action = SplitAction;
    type State = SplitAdapterState;
    type Error = SplitAdapterError;

    fn setup() -> Result<Self, Self::Error> {
        Self::setup_with_recipients(3, 1_000_000_000)
    }

    fn snapshot(&self) -> Result<Self::State, Self::Error> {
        let client = SplitContractClient::new(&self.env, &self.contract_id);
        let token_client = token::Client::new(&self.env, &self.token_id);

        let contract_token_balance = token_client.balance(&self.contract_id);
        let sender_token_balance = token_client.balance(&self.sender);

        let sdk_recipients: SdkVec<RecipientShare> = client
            .try_get_recipients()
            .map_err(|e| SplitAdapterError::QueryError(format!("{:?}", e)))?
            .map_err(|e| SplitAdapterError::QueryError(format!("{:?}", e)))?;

        let mut recipients = Vec::new();
        let mut total_shares_bps: u32 = 0;

        for r in sdk_recipients.iter() {
            total_shares_bps = total_shares_bps.saturating_add(r.share_bps);
            let total_allocated = client.get_total_allocated(&r.recipient);
            let total_claimed = client.get_total_claimed(&r.recipient);
            let unclaimed_balance = client.get_unclaimed_balance(&r.recipient);

            recipients.push(RecipientShareSnapshot {
                recipient: format!("{:?}", r.recipient),
                share_bps: r.share_bps,
                total_allocated,
                total_claimed,
                unclaimed_balance,
            });
        }

        let batch_count = client.batch_counter();
        let mut batches = Vec::new();

        for id in 1..=batch_count {
            if let Ok(Ok(batch)) = client.try_get_batch(&id) {
                batches.push(SplitBatchSnapshot {
                    batch_id: batch.id,
                    total_amount: batch.total_amount,
                    distributed_amount: batch.distributed_amount,
                    unallocated_dust: batch.unallocated_dust,
                    is_distributed: batch.is_distributed,
                });
            }
        }

        let total_deposited = client.get_total_deposited();
        let total_distributed = client.get_total_distributed();
        let total_dust = client.get_total_dust();

        Ok(SplitAdapterState {
            snapshot: SplitStateSnapshot {
                total_shares_bps,
                recipients,
                batches,
                total_deposited,
                total_distributed,
                total_dust,
                contract_token_balance: Some(contract_token_balance),
            },
            sender_token_balance,
        })
    }

    fn step(&mut self, action: &Self::Action) -> Result<ActionResult, Self::Error> {
        let client = SplitContractClient::new(&self.env, &self.contract_id);

        match action {
            SplitAction::DepositAndSplit { amount } => {
                let res = client.try_deposit_and_split(&self.sender, amount);
                match res {
                    Ok(Ok(_batch_id)) => Ok(ActionResult::Ok),
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
            SplitAction::Claim { recipient_idx } => {
                if *recipient_idx >= self.recipients.len() {
                    return Ok(ActionResult::Skipped("Invalid recipient index".into()));
                }
                let recipient = &self.recipients[*recipient_idx];
                let res = client.try_claim(recipient);
                match res {
                    Ok(Ok(_claimed)) => Ok(ActionResult::Ok),
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
            SplitAction::UpdateShares { shares_bps } => {
                if shares_bps.len() != self.recipients.len() {
                    return Ok(ActionResult::Skipped("Mismatched shares length".into()));
                }

                let mut sdk_recipients = sdk_vec![&self.env];
                for (i, &bps) in shares_bps.iter().enumerate() {
                    sdk_recipients.push_back(RecipientShare {
                        recipient: self.recipients[i].clone(),
                        share_bps: bps,
                    });
                }

                let res = client.try_update_shares(&self.admin, &sdk_recipients);
                match res {
                    Ok(Ok(())) => Ok(ActionResult::Ok),
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
        }
    }
}

impl SplitAdapter for SplitContractAdapter {
    fn inspect_split(state: &Self::State) -> SplitStateSnapshot {
        state.snapshot.clone()
    }

    fn classify_action(action: &Self::Action) -> Option<SplitActionKind> {
        match action {
            SplitAction::DepositAndSplit { amount } => Some(SplitActionKind::DepositAndSplit {
                batch_id: 0,
                amount: *amount,
            }),
            SplitAction::Claim { recipient_idx } => Some(SplitActionKind::ClaimShare {
                recipient: format!("{}", recipient_idx),
                amount: 0,
            }),
            SplitAction::UpdateShares { shares_bps } => {
                let sum: u32 = shares_bps.iter().sum();
                Some(SplitActionKind::ConfigureShares { total_bps: sum })
            }
        }
    }
}
