//! Adapter connecting `StreamPayContract` to `soroban-invariant-kit-core`.

use crate::contract::{
    compute_vested, Status, StreamPayContract, StreamPayContractClient,
};
use soroban_invariant_kit_core::{
    ActionResult, ContractAdapter, StreamSnapshot, StreamStatusKind, StreamingActionKind,
    StreamingAdapter, StreamingStateSnapshot,
};
use soroban_sdk::{
    testutils::Address as _, testutils::Ledger as _, token, Address, Env,
};

#[derive(thiserror::Error, Debug)]
pub enum StreamingAdapterError {
    #[error("Simulation setup error: {0}")]
    SetupError(String),
    #[error("Contract query error: {0}")]
    QueryError(String),
}

/// Abstract actions generated by fuzzer / property tests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StreamingAction {
    /// Create a new stream from sender to recipient with the given amount and duration.
    CreateStream { amount: i128, duration: u64 },
    /// Recipient withdraws all currently available vested tokens from the stream.
    Withdraw { stream_id: u64 },
    /// Cancel the stream, releasing vested funds to recipient and refunding remainder to sender.
    Cancel { stream_id: u64 },
    /// Sender adds more funds to an active stream.
    TopUp { stream_id: u64, amount: i128 },
    /// Sender extends the duration of an active stream.
    ExtendStream { stream_id: u64, extra_seconds: u64 },
    /// Advance the ledger timestamp by the given number of seconds.
    AdvanceLedgerTime { seconds: u64 },
}

/// State snapshot captured by the adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StreamingAdapterState {
    pub snapshot: StreamingStateSnapshot,
    pub sender_token_balance: i128,
    pub recipient_token_balance: i128,
}

/// Adapter for testing `StreamPayContract`.
pub struct StreamingContractAdapter {
    pub env: Env,
    pub contract_id: Address,
    pub token_id: Address,
    pub admin: Address,
    pub sender: Address,
    pub recipient: Address,
    pub initial_mint: i128,
}

impl StreamingContractAdapter {
    pub fn setup_with_mint(initial_mint: i128) -> Result<Self, StreamingAdapterError> {
        let env = Env::default();
        env.mock_all_auths();

        let admin = Address::generate(&env);
        let sender = Address::generate(&env);
        let recipient = Address::generate(&env);

        // Start ledger at a clean non-zero timestamp
        env.ledger().with_mut(|l| l.timestamp = 10_000);

        let token_id = env
            .register_stellar_asset_contract_v2(admin.clone())
            .address();
        let token_admin = token::StellarAssetClient::new(&env, &token_id);
        token_admin.mint(&sender, &initial_mint);

        let contract_id = env.register(StreamPayContract, ());
        let client = StreamPayContractClient::new(&env, &contract_id);
        client
            .try_initialize(&admin, &token_id)
            .map_err(|e| StreamingAdapterError::SetupError(format!("{:?}", e)))?
            .map_err(|e| StreamingAdapterError::SetupError(format!("{:?}", e)))?;

        Ok(Self {
            env,
            contract_id,
            token_id,
            admin,
            sender,
            recipient,
            initial_mint,
        })
    }
}

impl ContractAdapter for StreamingContractAdapter {
    type Action = StreamingAction;
    type State = StreamingAdapterState;
    type Error = StreamingAdapterError;

    fn setup() -> Result<Self, Self::Error> {
        Self::setup_with_mint(1_000_000_000)
    }

    fn snapshot(&self) -> Result<Self::State, Self::Error> {
        let client = StreamPayContractClient::new(&self.env, &self.contract_id);
        let token_client = token::Client::new(&self.env, &self.token_id);

        let timestamp = self.env.ledger().timestamp();
        let contract_token_balance = token_client.balance(&self.contract_id);
        let sender_token_balance = token_client.balance(&self.sender);
        let recipient_token_balance = token_client.balance(&self.recipient);

        let counter = client.stream_counter();
        let mut streams = Vec::new();
        let mut total_withdrawn: i128 = 0;

        for id in 1..=counter {
            if let Ok(stream) = client.try_get_stream(&id).map_err(|e| {
                StreamingAdapterError::QueryError(format!("Error fetching stream {}: {:?}", id, e))
            })? {
                let vested = compute_vested(&stream, timestamp).map_err(|e| {
                    StreamingAdapterError::QueryError(format!(
                        "Error calculating vested for stream {}: {:?}",
                        id, e
                    ))
                })?;

                let remaining = if stream.status == Status::Active {
                    stream.total.saturating_sub(stream.withdrawn)
                } else {
                    0
                };

                total_withdrawn = total_withdrawn.saturating_add(stream.withdrawn);

                let status = match stream.status {
                    Status::Active => StreamStatusKind::Active,
                    Status::Cancelled => StreamStatusKind::Cancelled,
                    Status::Completed => StreamStatusKind::Completed,
                };

                streams.push(StreamSnapshot {
                    id,
                    total: stream.total,
                    withdrawn: stream.withdrawn,
                    remaining,
                    refunded_sender: stream.refunded,
                    start_time: stream.start,
                    end_time: stream.end,
                    status,
                    accrued_vested: vested,
                });
            }
        }

        let total_deposited = client.get_total_deposited();
        let total_refunded = client.get_total_refunded();

        Ok(StreamingAdapterState {
            snapshot: StreamingStateSnapshot {
                timestamp,
                streams,
                total_deposited,
                total_withdrawn,
                total_refunded,
                contract_token_balance: Some(contract_token_balance),
            },
            sender_token_balance,
            recipient_token_balance,
        })
    }

    fn step(&mut self, action: &Self::Action) -> Result<ActionResult, Self::Error> {
        let client = StreamPayContractClient::new(&self.env, &self.contract_id);

        match action {
            StreamingAction::CreateStream { amount, duration } => {
                let start_time = self.env.ledger().timestamp();
                let end_time = start_time.saturating_add(*duration);
                let res = client.try_create_stream(
                    &self.sender,
                    &self.recipient,
                    amount,
                    &start_time,
                    &end_time,
                );
                match res {
                    Ok(Ok(_id)) => Ok(ActionResult::Ok),
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
            StreamingAction::Withdraw { stream_id } => {
                let res = client.try_withdraw(stream_id, &self.recipient);
                match res {
                    Ok(Ok(_withdrawn)) => Ok(ActionResult::Ok),
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
            StreamingAction::Cancel { stream_id } => {
                let res = client.try_cancel(stream_id, &self.sender);
                match res {
                    Ok(Ok(())) => Ok(ActionResult::Ok),
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
            StreamingAction::TopUp { stream_id, amount } => {
                let res = client.try_top_up(stream_id, &self.sender, amount);
                match res {
                    Ok(Ok(_new_total)) => Ok(ActionResult::Ok),
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
            StreamingAction::ExtendStream {
                stream_id,
                extra_seconds,
            } => {
                let stream_res = client.try_get_stream(stream_id);
                match stream_res {
                    Ok(Ok(stream)) => {
                        let new_end = stream.end.saturating_add(*extra_seconds);
                        let res = client.try_extend_stream(stream_id, &self.sender, &new_end);
                        match res {
                            Ok(Ok(())) => Ok(ActionResult::Ok),
                            Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                            Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                        }
                    }
                    Ok(Err(err)) => Ok(ActionResult::Reverted(format!("{:?}", err))),
                    Err(host_err) => Ok(ActionResult::Reverted(format!("{:?}", host_err))),
                }
            }
            StreamingAction::AdvanceLedgerTime { seconds } => {
                self.env.ledger().with_mut(|l| {
                    l.timestamp = l.timestamp.saturating_add(*seconds);
                });
                Ok(ActionResult::Ok)
            }
        }
    }
}

impl StreamingAdapter for StreamingContractAdapter {
    fn inspect_streaming(state: &Self::State) -> StreamingStateSnapshot {
        state.snapshot.clone()
    }

    fn classify_action(action: &Self::Action) -> Option<StreamingActionKind> {
        match action {
            StreamingAction::CreateStream { amount, duration } => {
                Some(StreamingActionKind::CreateStream {
                    id: 0,
                    amount: *amount,
                    start_time: 0,
                    end_time: *duration,
                })
            }
            StreamingAction::Withdraw { stream_id } => Some(StreamingActionKind::Withdraw {
                id: *stream_id,
                amount: 0,
            }),
            StreamingAction::Cancel { stream_id } => {
                Some(StreamingActionKind::Cancel { id: *stream_id })
            }
            StreamingAction::TopUp { stream_id, amount } => Some(StreamingActionKind::TopUp {
                id: *stream_id,
                amount: *amount,
            }),
            StreamingAction::ExtendStream {
                stream_id,
                extra_seconds,
            } => Some(StreamingActionKind::Extend {
                id: *stream_id,
                new_end: *extra_seconds,
            }),
            StreamingAction::AdvanceLedgerTime { seconds } => {
                Some(StreamingActionKind::AdvanceTime { seconds: *seconds })
            }
        }
    }
}
