//! ContractAdapter trait and action execution types.
//!
//! An **adapter** provides an abstraction boundary between the invariant
//! testing harness and the concrete Soroban contract(s) under test.
//!
//! Rather than rewriting contracts for testing, contract authors implement
//! [`ContractAdapter`] to map abstract fuzzer actions into concrete contract calls,
//! manage simulated environments (`soroban_sdk::Env`), and extract typed state snapshots.

/// Outcome of applying an action via [`ContractAdapter::step`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ActionResult {
    /// The action completed successfully and state was updated.
    Ok,
    /// The action resulted in a transaction revert or caught contract error
    /// (e.g., authorization failure, precondition not met).
    Reverted(String),
    /// The action was skipped because it is not applicable in the current state.
    Skipped(String),
}

impl ActionResult {
    #[inline]
    pub fn is_ok(&self) -> bool {
        matches!(self, ActionResult::Ok)
    }

    #[inline]
    pub fn is_reverted(&self) -> bool {
        matches!(self, ActionResult::Reverted(_))
    }

    #[inline]
    pub fn is_skipped(&self) -> bool {
        matches!(self, ActionResult::Skipped(_))
    }
}

/// The bridge between invariant testing engines and concrete contracts.
///
/// Implementors specify:
/// - `Action`: Abstract operations generated by the test runner (fuzzer / proptest).
/// - `State`: An observable, immutable snapshot of the system state.
/// - `Error`: Harness or environment errors that prevent test execution.
pub trait ContractAdapter: 'static {
    /// Abstract action generated by the testing engine.
    type Action: std::fmt::Debug + Clone;

    /// Observable state snapshot of the contract and associated dependencies.
    type State: std::fmt::Debug + Clone;

    /// Fatal error encountered during setup or step execution.
    type Error: std::error::Error + Send + Sync + 'static;

    /// Initializes a fresh testing environment, deploying all required contracts
    /// and seeding any initial ledger or token states.
    fn setup() -> Result<Self, Self::Error>
    where
        Self: Sized;

    /// Extracts an immutable snapshot of the current state of the system.
    fn snapshot(&self) -> Result<Self::State, Self::Error>;

    /// Executes a single abstract action against the contracts under test.
    ///
    /// The method returns:
    /// - `Ok(ActionResult::Ok)` if the invocation succeeded.
    /// - `Ok(ActionResult::Reverted(reason))` if the invocation failed / reverted.
    /// - `Ok(ActionResult::Skipped(reason))` if the action could not be run.
    /// - `Err(Self::Error)` if a fatal test harness or simulation error occurred.
    fn step(&mut self, action: &Self::Action) -> Result<ActionResult, Self::Error>;
}
